//! Day Skies — a weather app built with [Day](https://daybrite.dev). `root()` is the whole UI,
//! shared by every platform. A `nav` over the user's city list is the adaptive shell: a
//! sidebar + detail split on desktop, a list that pushes the detail on mobile. The list itself
//! is editable (`cities.rs`) and persists via day-part-prefs; each city's weather lives in its
//! own reactive signal, fed by the data layer in `weather.rs`.

use day::prelude::*;
use std::cell::RefCell;
use std::rc::Rc;

mod cities;
mod icons;
mod settings;
mod ui;
mod weather;

use cities::City;
use weather::Weather;

// The mobile / embedded entry point. Expands to the export each platform's shell binds
// against — and to nothing at all on a plain cargo desktop build, where src/main.rs is the
// entry instead.
day::day_start!("Day Skies", root);

/// Typed resource + localization constants generated by `day-build` from `resource/` (see build.rs):
/// `res::str::<key>()` for every Fluent message, with the message's params as typed arguments —
/// a missing key or wrong arity is a compile error — plus `res::locales`, the catalog of every
/// locale directory, which `root()` installs.
pub mod res {
    include!(concat!(env!("OUT_DIR"), "/day_resources.rs"));
}

/// Per-city weather resources (docs/async.md), memoized by place id so navigating between
/// cities (which rebuilds the detail pane) reuses the same loaded data.
///
/// APP-wide (docs/state.md), not per-window: it is a fetch CACHE over shared data, and two
/// windows showing the same city should read one load rather than each starting its own.
#[derive(Clone)]
struct Forecasts(Rc<RefCell<Vec<(String, day::reactive::Resource<Weather>)>>>);

impl Ambient for Forecasts {
    fn create() -> Self {
        Forecasts(Rc::new(RefCell::new(Vec::new())))
    }
}

/// Get (creating on first call) the weather resource for a city. The resource TRACKS the
/// Save-applied host (`settings::host()`), so applying a new host refetches by itself; mock data
/// resolves synchronously inside the fetcher; the live path awaits the platform fetch through
/// `fetch_future` (docs/http.md) — cancellation and latest-wins ride the Resource.
fn resource_for(city: &City) -> day::reactive::Resource<Weather> {
    let cache = Forecasts::app().0;
    if let Some((_, r)) = cache.borrow().iter().find(|(id, _)| *id == city.id) {
        return *r;
    }
    // Root scope, NOT the calling page's build scope: the resource must outlive the detail
    // pane that first touched it (a page-scoped resource would be disposed on navigation and
    // the memoized handle would go dead — the settings Store's app-scope rationale).
    let fetch_city = city.clone();
    let r = day::reactive::Scope::root().enter(|| {
        day::reactive::Resource::new(settings::host, move |host| {
            weather::load(fetch_city.clone(), host)
        })
    });
    cache.borrow_mut().push((city.id.clone(), r));
    r
}

/// Refetch every city (the settings Save action). Save also writes the applied-host signal the
/// resources track, so a CHANGED host refetches twice-deduped into one run (both dependencies
/// dirty in the same drain); an unchanged host still refetches — Save always re-checks.
pub(crate) fn reload_all() {
    for (_, r) in Forecasts::app().0.borrow().iter() {
        r.refetch();
    }
}

/// Forget a city's memoized resource — removal, or an edit that may have moved its coordinates
/// (the next view rebuilds it fresh). The dropped resource's nodes stay in the root scope until
/// exit; that leak is bounded by the user's edit count.
pub(crate) fn drop_state(id: &str) {
    Forecasts::app().0.borrow_mut().retain(|(k, _)| k != id);
}

/// Everything ONE WINDOW owns (docs/state.md): which city it is showing. `Copy`, because a
/// `Signal` is a handle — so it rides into the nav's closures without ceremony.
///
/// File ▸ New Window builds `window_shell` again, and `Ambient::scoped` gives that build its own
/// `Scene`: the two windows browse the same city list independently.
#[derive(Clone, Copy)]
pub(crate) struct Scene {
    section: Signal<Option<String>>,
}

impl Ambient for Scene {
    fn create() -> Self {
        // Open on the first city so both desktop and mobile show weather immediately.
        let first = cities::cities()
            .get_untracked()
            .first()
            .map(|c| c.id.clone());
        Scene {
            section: Signal::new(first),
        }
    }
}

fn city_page(city: City) -> impl Piece {
    let state = resource_for(&city).signal();
    let page = ui::weather_page(city.clone(), state);
    // Desktop (docs/windows.md): right-click ▸ Open in New Window — a per-city Normal
    // window (same-kind windows group as native macOS tabs). `city_page_for` re-resolves
    // by id, so the window follows the live list.
    if capability(Cap::MultiWindow) == Support::Unsupported {
        return Either::Left(page);
    }
    let id = city.id.clone();
    let title = city.name.clone();
    Either::Right(page.context_menu(vec![
        menu_item(res::str::open_in_new_window().format()).action(move || {
            let id = id.clone();
            day::open_window(
                None,
                day::WindowOptions {
                    title: title.clone(),
                    size: Size::new(700.0, 800.0),
                    min_size: None,
                    app_name: None,
                    ..Default::default()
                },
                day::WindowKind::Normal,
                move || city_page_for(&id),
            );
        }),
    ]))
}

/// The `.destination` for a data-driven city key: look the city up in the live list. A key that
/// just vanished (removed mid-navigation) gets an empty pane — the selection resets right after.
fn city_page_for(id: &str) -> impl Piece + use<> {
    match cities::cities()
        .get_untracked()
        .into_iter()
        .find(|c| c.id == id)
    {
        Some(city) => Either::Left(city_page(city)),
        None => Either::Right(spacer()),
    }
}

pub fn root() -> impl Piece {
    // Every locale under `resource/locales/` (en, fr, ar, zh-CN), embedded and registered by the
    // generated catalog — adding a language is a new directory, nothing to edit here.
    res::locales::install();
    // Persisted language/theme overrides, before the first page builds.
    settings::apply_startup();
    // The Preferences window (docs/windows.md): the settings page as a singleton window on
    // desktop (auto Settings…/⌘, menu item), the cover fallback on mobile. The sidebar's
    // "settings" item keeps working everywhere — same page, two entry points.
    day::register_preferences_with(
        day::WindowOptions {
            title: res::str::settings_title().format(),
            size: Size::new(560.0, 720.0),
            min_size: None,
            app_name: None,
            ..Default::default()
        },
        settings::settings_page,
    );

    // Create every stored city's resource in the (permanent) root scope and start loading now.
    for city in cities::cities().get_untracked() {
        let _ = resource_for(&city);
    }
    // File ▸ New Window (docs/windows.md): the SAME shell again, which is exactly why the
    // selection lives on a `Scene` rather than in a global — each call gets its own.
    day::register_new_window(window_shell);

    window_shell()
}

/// One window's UI — the first window's, and every File ▸ New Window's.
fn window_shell() -> impl Piece {
    let city_list = cities::cities();
    Scene::scoped(move |scene| {
        nav(scene.section)
            .style(NavStyle::Sidebar)
            .title(res::str::app_title())
            .header(sidebar_header)
            // The city rows re-derive whenever the list changes (add/edit/remove on the
            // Settings page). They keep the floating transparent chrome over the full-bleed sky
            // (android edge-to-edge); Settings keeps the standard opaque bar.
            .items(
                move || city_list.get(),
                |c: &City| item(c.id.clone(), cities::title(c)).immersive(),
            )
            .destination(|id: &Option<String>| match id {
                Some(id) => Either::Left(city_page_for(id)),
                None => Either::Right(spacer()),
            })
            .item(
                "settings".to_string(),
                res::str::settings_title(),
                settings::settings_page,
            )
            .id("nav")
    })
}

fn sidebar_header() -> impl Piece {
    column((
        label(res::str::app_title())
            .font(Font::Headline)
            .id("app-title"),
        label(res::str::app_tagline()).font(Font::Caption),
    ))
    .spacing(2.0)
    .align(HAlign::Leading)
    .padding(12.0)
}
