//! Day Skies — a weather app built with [Day](https://daybrite.dev). `root()` is the whole UI,
//! shared by every platform. A `selector` over the user's city list is the adaptive shell: a
//! sidebar + detail split on desktop, a list that pushes the detail on mobile. The list itself
//! is editable (`cities.rs`) and persists via day-part-prefs; each city's weather lives in its
//! own reactive signal, fed by the data layer in `weather.rs`.

use day::prelude::*;
use std::cell::RefCell;

mod cities;
mod icons;
mod settings;
mod ui;
mod weather;

use cities::City;
use weather::Weather;

/// Typed resource + localization constants generated by `day-build` from `resource/` (see build.rs):
/// `res::str::<key>()` for every Fluent message, with the message's params as typed arguments —
/// a missing key or wrong arity is a compile error — plus `res::locales`, the catalog of every
/// locale directory, which `root()` installs.
pub mod res {
    include!(concat!(env!("OUT_DIR"), "/day_resources.rs"));
}

thread_local! {
    /// Per-city weather resources (docs/async.md), memoized by place id so navigating between
    /// cities (which rebuilds the detail pane) reuses the same loaded data.
    static STATES: RefCell<Vec<(String, day::reactive::Resource<Weather>)>> =
        const { RefCell::new(Vec::new()) };
}

/// Get (creating on first call) the weather resource for a city. The resource TRACKS the
/// Save-applied host (`settings::host()`), so applying a new host refetches by itself; mock data
/// resolves synchronously inside the fetcher; the live path awaits the platform fetch through
/// `fetch_future` (docs/http.md) — cancellation and latest-wins ride the Resource.
fn resource_for(city: &City) -> day::reactive::Resource<Weather> {
    STATES.with(|cell| {
        if let Some((_, r)) = cell.borrow().iter().find(|(id, _)| *id == city.id) {
            return *r;
        }
        // Root scope, NOT the calling page's build scope: the resource must outlive the detail
        // pane that first touched it (a page-scoped resource would be disposed on navigation and
        // the memoized handle would go dead — the settings Store's detached-scope rationale).
        let fetch_city = city.clone();
        let r = day::reactive::Scope::root().enter(|| {
            day::reactive::Resource::new(settings::host, move |host| {
                weather::load(fetch_city.clone(), host)
            })
        });
        cell.borrow_mut().push((city.id.clone(), r));
        r
    })
}

/// Refetch every city (the settings Save action). Save also writes the applied-host signal the
/// resources track, so a CHANGED host refetches twice-deduped into one run (both dependencies
/// dirty in the same drain); an unchanged host still refetches — Save always re-checks.
pub(crate) fn reload_all() {
    STATES.with(|cell| {
        for (_, r) in cell.borrow().iter() {
            r.refetch();
        }
    });
}

/// Forget a city's memoized resource — removal, or an edit that may have moved its coordinates
/// (the next view rebuilds it fresh). The dropped resource's nodes stay in the root scope until
/// exit; that leak is bounded by the user's edit count.
pub(crate) fn drop_state(id: &str) {
    STATES.with(|cell| cell.borrow_mut().retain(|(k, _)| k != id));
}

fn city_page(city: City) -> AnyPiece {
    let state = resource_for(&city).signal();
    let page = ui::weather_page(city.clone(), state);
    // Desktop (docs/windows.md): right-click ▸ Open in New Window — a per-city Normal
    // window (same-kind windows group as native macOS tabs). `city_page_for` re-resolves
    // by id, so the window follows the live list.
    if capability(Cap::MultiWindow) == Support::Unsupported {
        return page;
    }
    let id = city.id.clone();
    let title = city.name.clone();
    page.context_menu(vec![
        menu_item(res::str::open_in_new_window().format()).action(move || {
            let id = id.clone();
            day::open_window(
                None,
                day::WindowOptions {
                    title: title.clone(),
                    size: Size::new(700.0, 800.0),
                    min_size: None,
                    app_name: None,
                    ..Default::default()
                },
                day::WindowKind::Normal,
                move || city_page_for(&id),
            );
        }),
    ])
}

/// The `.destination` for a data-driven city key: look the city up in the live list. A key that
/// just vanished (removed mid-navigation) gets an empty pane — the selection resets right after.
fn city_page_for(id: &str) -> AnyPiece {
    match cities::cities()
        .get_untracked()
        .into_iter()
        .find(|c| c.id == id)
    {
        Some(city) => city_page(city),
        None => spacer().any(),
    }
}

pub fn root() -> AnyPiece {
    // Every locale under `resource/locales/` (en, fr, ar, zh-CN), embedded and registered by the
    // generated catalog — adding a language is a new directory, nothing to edit here.
    res::locales::install();
    // Persisted language/theme overrides, before the first page builds.
    settings::apply_startup();
    // The Preferences window (docs/windows.md): the settings page as a singleton window on
    // desktop (auto Settings…/⌘, menu item), the cover fallback on mobile. The sidebar's
    // "settings" item keeps working everywhere — same page, two entry points.
    day::register_preferences_with(
        day::WindowOptions {
            title: res::str::settings_title().format(),
            size: Size::new(560.0, 720.0),
            min_size: None,
            app_name: None,
            ..Default::default()
        },
        settings::settings_page,
    );

    // Create every stored city's resource in the (permanent) root scope and start loading now.
    let city_list = cities::cities();
    for city in city_list.get_untracked() {
        let _ = resource_for(&city);
    }

    // Open on the first city so both desktop and mobile show weather immediately.
    let first = city_list.get_untracked().first().map(|c| c.id.clone());
    let section: Signal<Option<String>> = Signal::new(first);
    selector(section)
        .style(SelectorStyle::Sidebar)
        .title(res::str::app_title())
        .header(sidebar_header)
        // The city rows re-derive whenever the list changes (add/edit/remove on the
        // Settings page). They keep the floating transparent chrome over the full-bleed sky
        // (android edge-to-edge); Settings keeps the standard opaque bar.
        .items(
            move || city_list.get(),
            |c: &City| item(c.id.clone(), cities::title(c)).immersive(),
        )
        .destination(|id: &Option<String>| match id {
            Some(id) => city_page_for(id),
            None => spacer().any(),
        })
        .item(
            "settings".to_string(),
            res::str::settings_title(),
            settings::settings_page,
        )
        .id("nav")
        .any()
}

fn sidebar_header() -> AnyPiece {
    column((
        label(res::str::app_title())
            .font(Font::Headline)
            .id("app-title"),
        label(res::str::app_tagline()).font(Font::Caption),
    ))
    .spacing(2.0)
    .align(HAlign::Leading)
    .padding(12.0)
    .any()
}

// The mobile / embedded entry point. Expands to the export each platform's shell binds
// against — and to nothing at all on a plain cargo desktop build, where src/main.rs is the
// entry instead.
day::day_main!("Day Skies", root);
